name: arrayscope
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.20
  - pyside6>=6.4
  - pyqtgraph>=0.14
  - h5py>=3.0
  - scipy>=1.7
  - pyfftw
  - pydicom>=2.4
  - nibabel>=4.0
  - imageio>=2.9
  - imageio-ffmpeg>=0.4
  - pillow>=8.0
  - psutil
  - pytest
  - hypothesis
  - pip
  - pip:
      - -e .
      - pytest-qt>=4.4.0
      - qt-material-icons>=0.3.0
