# -*- mode: python ; coding: utf-8 -*-
"""Shared PyInstaller spec for every ArrayScope binary bundle.

Used by packaging/linux/build_appimage.sh, packaging/windows/build_installer.ps1
and packaging/macos/build_dmg.sh. Build from the repository root:

    pyinstaller --noconfirm packaging/pyinstaller/arrayscope.spec

Produces a one-directory bundle at dist/ArrayScope (dist/ArrayScope.app on
macOS). The interpreter and all dependencies are inside; end users never see
Python.
"""

import sys
from pathlib import Path

from PyInstaller.utils.hooks import (
    collect_data_files,
    collect_submodules,
    copy_metadata,
)

SPEC_DIR = Path(SPECPATH).resolve()
REPO_ROOT = SPEC_DIR.parents[1]
ICON_DIR = REPO_ROOT / "arrayscope" / "resources" / "icons"

_version_ns = {}
exec((REPO_ROOT / "arrayscope" / "_version.py").read_text(), _version_ns)
VERSION = _version_ns["__version__"]

datas = []
# Package data inside arrayscope/ (icon set) is not source code, so PyInstaller
# does not pick it up from imports alone.
datas += collect_data_files("arrayscope")
# Colormap tables and Material icon SVGs are loaded from package data at runtime.
datas += collect_data_files("cmcrameri")
datas += collect_data_files("qt_material_icons")
# imageio reads its own distribution version via importlib.metadata at import
# time; without the .dist-info it raises PackageNotFoundError and MP4/WebM
# export silently disables itself. (Verified 2026-07 local build.)
datas += copy_metadata("imageio")
datas += copy_metadata("imageio_ffmpeg")

# The io interpreters, operations registry and Qt widgets import lazily; make
# sure the whole package is present rather than only what the entry imports.
hiddenimports = collect_submodules("arrayscope")
# Verified misses (2026-07 local build): imageio and nibabel are only imported
# inside functions/try-except and Analysis dropped them despite being hard
# dependencies — video export and NIfTI loading silently degrade without
# them. Their own submodules load lazily (imageio plugins, nibabel formats),
# so collect them wholesale. imageio_ffmpeg's hook bundles the ffmpeg binary.
hiddenimports += collect_submodules("imageio")
hiddenimports += collect_submodules("nibabel")
hiddenimports += ["imageio_ffmpeg"]

# Trim libraries PyInstaller would otherwise drag in via optional imports.
excludes = [
    "tkinter",
    "matplotlib",
    "IPython",
    "jupyter",
    "PyQt5",
    "PyQt6",
    "PySide2",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.Qt3DInput",
    "PySide6.Qt3DLogic",
    "PySide6.Qt3DAnimation",
    "PySide6.Qt3DExtras",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtQuick3D",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
]

if sys.platform == "win32":
    app_icon = str(ICON_DIR / "arrayscope.ico")
elif sys.platform == "darwin":
    # Generated by packaging/macos/build_dmg.sh (iconutil is macOS-only).
    app_icon = str(REPO_ROOT / "build" / "icons" / "arrayscope.icns")
else:
    app_icon = None

a = Analysis(
    [str(SPEC_DIR / "entry.py")],
    pathex=[str(REPO_ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    exclude_binaries=True,
    name="ArrayScope",
    debug=False,
    strip=False,
    upx=False,
    # Linux keeps a console binary so terminal use (arrayscope file.npy) still
    # prints; GUI launches via .desktop never show a terminal anyway. Windows
    # and macOS are windowed viewer builds.
    console=(sys.platform not in ("win32", "darwin")),
    icon=app_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="ArrayScope",
)

if sys.platform == "darwin":
    # Mirrors arrayscope/desktop/filetypes.py (owned + shared types, Viewer role).
    _document_types = [
        ("NumPy array", ["npy"]),
        ("NumPy array archive", ["npz"]),
        ("BART complex-float array", ["cfl"]),
        ("Philips XML/REC image", ["rec"]),
        ("NIfTI neuroimaging data", ["nii", "nii.gz"]),
        ("MATLAB data file", ["mat"]),
        ("DICOM image", ["dcm"]),
        ("HDF5 data file", ["h5", "hdf5"]),
    ]
    app = BUNDLE(
        coll,
        name="ArrayScope.app",
        icon=app_icon,
        bundle_identifier="io.github.roosted7.arrayscope",
        version=VERSION,
        info_plist={
            "CFBundleName": "ArrayScope",
            "CFBundleDisplayName": "ArrayScope",
            "CFBundleShortVersionString": VERSION,
            "CFBundleVersion": VERSION,
            "NSHighResolutionCapable": True,
            "NSPrincipalClass": "NSApplication",
            "CFBundleDocumentTypes": [
                {
                    "CFBundleTypeName": name,
                    "CFBundleTypeRole": "Viewer",
                    "CFBundleTypeExtensions": exts,
                }
                for name, exts in _document_types
            ],
        },
    )
